[tool.semantic_release]
version_variables = ["rebulk/__version__.py:__version__"]
commit_message = "chore(release): release v{version}"
commit_author = "github-actions <actions@github.com>"

[tool.pytest.ini_options]
addopts = "--ignore=setup.py --ignore=build --doctest-modules --doctest-glob='README.rst'"
